name: Ejecutar prueba automatizada y actualizar Jira

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # Programado para ejecutarse todos los días a medianoche

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Ejecutar prueba y actualizar Jira
      run: |
        python main_update.py

    env:
        JIRA_API_TOKEN: ${{ ATATT3xFfGF07d8fddMMTUZOnJhzXXLG40txpySkvjsDJaXyI6TmvzqDlOxK8dOQpls_iS9YyFs9oLqQ6D4PRr2oxXkCMpU7Xnbzd1FMUuT3cSQA9jnwjG0v6mG8bJ6soSnwU2PIPn7GD1zdDvDTIlKks79MhIQDrNV-Qtn6FY8wdojpCkba0Wk=ABE9E89C }}
        JIRA_USER: ${{ carlosmarsh@hotmail.com }}
        JIRA_URL: ${{ https://carlosprueba.atlassian.net }}
